name: github_search
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.5
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  flutter_slidable: ^3.1.1
  freezed_annotation: ^2.4.1
  go_router: ^14.2.1
  hooks_riverpod: ^2.5.1
  package_info_plus: ^8.0.2
  provider: ^6.1.2
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  flutter_lints: ^3.0.0
  dio: ^5.5.0+1
  settings_ui: ^2.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.5.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/
